apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecom
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ModiniPadmaSree/ecom-k8s.git'
    targetRevision: main
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ecom
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
