apiVersion: v1
kind: Secret
metadata:
  name: ecom-backend-secret
  namespace: ecom
type: Opaque
stringData:
  MONGO_URI: "REPLACE_WITH_MONGO_URI"
  JWT_SECRET: "REPLACE_WITH_JWT_SECRET"
  SMTP_PASSWORD: "REPLACE_WITH_SMTP_PASSWORD"
  STRIPE_SECRET_KEY: "REPLACE_WITH_STRIPE_SECRET_KEY"
