apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace }}
data:
  PORT: {{ .Values.backend.config.PORT }}
  JWT_EXPIRE: {{ .Values.backend.config.JWT_EXPIRE }}
  COOKIE_EXPIRE: {{ .Values.backend.config.COOKIE_EXPIRE }}
  SMTP_HOST: {{ .Values.backend.config.SMTP_HOST }}
  SMTP_PORT: {{ .Values.backend.config.SMTP_PORT }}
  SMTP_SERVICE: {{ .Values.backend.config.SMTP_SERVICE }}
  FRONTEND_URL: {{ .Values.backend.config.FRONTEND_URL }}
