apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecom
  namespace: argo-cd
spec:
  project: default

  source:
    repoURL: https://github.com/ModiniPadmaSree/ecom-k8s.git
    targetRevision: main
    path: base

  destination:
    server: https://kubernetes.default.svc
    namespace: ecom

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
