apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: e-com
data:
  PORT: "5000"
  JWT_EXPIRE: "30d"
  COOKIE_EXPIRE: "30"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "465"
  SMTP_SERVICE: "gmail"
  FRONTEND_URL: "http://k8s-ecom-ecomingr-56c89b259d-1337609387.us-east-1.elb.amazonaws.com"
